# Generated by Django 6.1.1 on 2026-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGV_mismary', '0002_cliente_telefono_alter_cliente_nombre_deuda_abono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=20),
        ),
    ]
