# Generated by Django 6.1.1 on 2026-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGV_mismary', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
